/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OsRouteRouteImport } from './routes/os/route'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnBookRouteImport } from './routes/en/book'
import { Route as OsIndexRouteImport } from './routes/os/index'
import { Route as OsCalendarRouteImport } from './routes/os/calendar'
import { Route as OsPaymentsRouteImport } from './routes/os/payments'
import { Route as OsSettingsRouteImport } from './routes/os/settings'
import { Route as OsBookingsIndexRouteImport } from './routes/os/bookings/index'
import { Route as OsBookingsIdRouteImport } from './routes/os/bookings/$id'
import { Route as OsCustomersIndexRouteImport } from './routes/os/customers/index'
import { Route as OsCustomersIdRouteImport } from './routes/os/customers/$id'
import { Route as OsLeadsIndexRouteImport } from './routes/os/leads/index'
import { Route as OsLeadsIdRouteImport } from './routes/os/leads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRouteRoute = OsRouteRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBookRoute = EnBookRouteImport.update({
  id: '/en/book',
  path: '/en/book',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsCalendarRoute = OsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsPaymentsRoute = OsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsSettingsRoute = OsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsBookingsIndexRoute = OsBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsBookingsIdRoute = OsBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsCustomersIndexRoute = OsCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsCustomersIdRoute = OsCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsLeadsIndexRoute = OsLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => OsRouteRoute,
} as any)
const OsLeadsIdRoute = OsLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => OsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/os': typeof OsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/en/book': typeof EnBookRoute
  '/os/calendar': typeof OsCalendarRoute
  '/os/payments': typeof OsPaymentsRoute
  '/os/settings': typeof OsSettingsRoute
  '/en/': typeof EnIndexRoute
  '/os/': typeof OsIndexRoute
  '/os/bookings/$id': typeof OsBookingsIdRoute
  '/os/customers/$id': typeof OsCustomersIdRoute
  '/os/leads/$id': typeof OsLeadsIdRoute
  '/os/bookings/': typeof OsBookingsIndexRoute
  '/os/customers/': typeof OsCustomersIndexRoute
  '/os/leads/': typeof OsLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/en/book': typeof EnBookRoute
  '/os/calendar': typeof OsCalendarRoute
  '/os/payments': typeof OsPaymentsRoute
  '/os/settings': typeof OsSettingsRoute
  '/en': typeof EnIndexRoute
  '/os': typeof OsIndexRoute
  '/os/bookings/$id': typeof OsBookingsIdRoute
  '/os/customers/$id': typeof OsCustomersIdRoute
  '/os/leads/$id': typeof OsLeadsIdRoute
  '/os/bookings': typeof OsBookingsIndexRoute
  '/os/customers': typeof OsCustomersIndexRoute
  '/os/leads': typeof OsLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/os': typeof OsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reservar': typeof ReservarRoute
  '/en/book': typeof EnBookRoute
  '/os/calendar': typeof OsCalendarRoute
  '/os/payments': typeof OsPaymentsRoute
  '/os/settings': typeof OsSettingsRoute
  '/en/': typeof EnIndexRoute
  '/os/': typeof OsIndexRoute
  '/os/bookings/$id': typeof OsBookingsIdRoute
  '/os/customers/$id': typeof OsCustomersIdRoute
  '/os/leads/$id': typeof OsLeadsIdRoute
  '/os/bookings/': typeof OsBookingsIndexRoute
  '/os/customers/': typeof OsCustomersIndexRoute
  '/os/leads/': typeof OsLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/os'
    | '/login'
    | '/reservar'
    | '/en/book'
    | '/os/calendar'
    | '/os/payments'
    | '/os/settings'
    | '/en/'
    | '/os/'
    | '/os/bookings/$id'
    | '/os/customers/$id'
    | '/os/leads/$id'
    | '/os/bookings/'
    | '/os/customers/'
    | '/os/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reservar'
    | '/en/book'
    | '/os/calendar'
    | '/os/payments'
    | '/os/settings'
    | '/en'
    | '/os'
    | '/os/bookings/$id'
    | '/os/customers/$id'
    | '/os/leads/$id'
    | '/os/bookings'
    | '/os/customers'
    | '/os/leads'
  id:
    | '__root__'
    | '/'
    | '/os'
    | '/login'
    | '/reservar'
    | '/en/book'
    | '/os/calendar'
    | '/os/payments'
    | '/os/settings'
    | '/en/'
    | '/os/'
    | '/os/bookings/$id'
    | '/os/customers/$id'
    | '/os/leads/$id'
    | '/os/bookings/'
    | '/os/customers/'
    | '/os/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OsRouteRoute: typeof OsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReservarRoute: typeof ReservarRoute
  EnBookRoute: typeof EnBookRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/book': {
      id: '/en/book'
      path: '/en/book'
      fullPath: '/en/book'
      preLoaderRoute: typeof EnBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/': {
      id: '/os/'
      path: '/'
      fullPath: '/os/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/calendar': {
      id: '/os/calendar'
      path: '/calendar'
      fullPath: '/os/calendar'
      preLoaderRoute: typeof OsCalendarRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/payments': {
      id: '/os/payments'
      path: '/payments'
      fullPath: '/os/payments'
      preLoaderRoute: typeof OsPaymentsRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/settings': {
      id: '/os/settings'
      path: '/settings'
      fullPath: '/os/settings'
      preLoaderRoute: typeof OsSettingsRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/bookings/': {
      id: '/os/bookings/'
      path: '/bookings'
      fullPath: '/os/bookings/'
      preLoaderRoute: typeof OsBookingsIndexRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/bookings/$id': {
      id: '/os/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/os/bookings/$id'
      preLoaderRoute: typeof OsBookingsIdRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/customers/': {
      id: '/os/customers/'
      path: '/customers'
      fullPath: '/os/customers/'
      preLoaderRoute: typeof OsCustomersIndexRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/customers/$id': {
      id: '/os/customers/$id'
      path: '/customers/$id'
      fullPath: '/os/customers/$id'
      preLoaderRoute: typeof OsCustomersIdRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/leads/': {
      id: '/os/leads/'
      path: '/leads'
      fullPath: '/os/leads/'
      preLoaderRoute: typeof OsLeadsIndexRouteImport
      parentRoute: typeof OsRouteRoute
    }
    '/os/leads/$id': {
      id: '/os/leads/$id'
      path: '/leads/$id'
      fullPath: '/os/leads/$id'
      preLoaderRoute: typeof OsLeadsIdRouteImport
      parentRoute: typeof OsRouteRoute
    }
  }
}

interface OsRouteRouteChildren {
  OsCalendarRoute: typeof OsCalendarRoute
  OsPaymentsRoute: typeof OsPaymentsRoute
  OsSettingsRoute: typeof OsSettingsRoute
  OsIndexRoute: typeof OsIndexRoute
  OsBookingsIdRoute: typeof OsBookingsIdRoute
  OsCustomersIdRoute: typeof OsCustomersIdRoute
  OsLeadsIdRoute: typeof OsLeadsIdRoute
  OsBookingsIndexRoute: typeof OsBookingsIndexRoute
  OsCustomersIndexRoute: typeof OsCustomersIndexRoute
  OsLeadsIndexRoute: typeof OsLeadsIndexRoute
}

const OsRouteRouteChildren: OsRouteRouteChildren = {
  OsCalendarRoute: OsCalendarRoute,
  OsPaymentsRoute: OsPaymentsRoute,
  OsSettingsRoute: OsSettingsRoute,
  OsIndexRoute: OsIndexRoute,
  OsBookingsIdRoute: OsBookingsIdRoute,
  OsCustomersIdRoute: OsCustomersIdRoute,
  OsLeadsIdRoute: OsLeadsIdRoute,
  OsBookingsIndexRoute: OsBookingsIndexRoute,
  OsCustomersIndexRoute: OsCustomersIndexRoute,
  OsLeadsIndexRoute: OsLeadsIndexRoute,
}

const OsRouteRouteWithChildren =
  OsRouteRoute._addFileChildren(OsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OsRouteRoute: OsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ReservarRoute: ReservarRoute,
  EnBookRoute: EnBookRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
